name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm publint
      - run: pnpm size-limit

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm nx release -y
